GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO garfex_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO garfex_app;

ALTER DEFAULT PRIVILEGES FOR ROLE garfex_admin IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO garfex_app;
ALTER DEFAULT PRIVILEGES FOR ROLE garfex_admin IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO garfex_app;
