ALTER DEFAULT PRIVILEGES FOR ROLE garfex_admin IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM garfex_app;
ALTER DEFAULT PRIVILEGES FOR ROLE garfex_admin IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM garfex_app;

REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM garfex_app;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM garfex_app;
